/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:57 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {
    import mx.collections.ListCollectionView;
    

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.BundleRequest")]
    public class BundleRequest {
        
        private var _skipAndAmount:ListCollectionView;

        public function get skipAndAmount():ListCollectionView {
            return _skipAndAmount;
        }

    }
}