/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:54 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.Domain")]
    public class Domain {

        private var _brand:String;
        private var _domain:String;
        private var _id:Number;
        private var _sharedQuota:Boolean;
        private var _timezone:String;
        private var _categoryCollection:CategoryCollection;

        public function set brand(value:String):void {
            _brand = value;
        }
        public function get brand():String {
            return _brand;
        }

        public function set domain(value:String):void {
            _domain = value;
        }
        public function get domain():String {
            return _domain;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set sharedQuota(value:Boolean):void {
            _sharedQuota = value;
        }
        public function get sharedQuota():Boolean {
            return _sharedQuota;
        }

        public function set timezone(value:String):void {
            _timezone = value;
        }
        public function get timezone():String {
            return _timezone;
        }

        public function set categoryCollection(value:CategoryCollection):void {
            _categoryCollection = value;
        }
        public function get categoryCollection():CategoryCollection {
            return _categoryCollection;
        }
    }
}