package net.java.dev.cejug.classifieds.view.jsf;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import net.java.dev.cejug.classifieds.model.entity.Advertisement;
import net.java.dev.cejug.classifieds.model.service.AdvertisementService;

/**
 * This class is responsible for the operations related to advertisement.
 * 
 * @author Rafael Carneiro [rafaelcarneirob@gmail.com]
 * @author Tarso Bessa [tarso.bessa@gmail.com]
 */
public class AdvertisementBean {
	/**
	 * The actual advertisement this bean is editing or publishing.
	 */
	private Advertisement advertisement = new Advertisement();
	/**
	 * The advertisement service to communicate with the server
	 */
	private AdvertisementService adsService;

	/**
	 * Publish the advertisement.
	 * @param actionEvent the event generated by component
	 */
	public void publish(ActionEvent actionEvent) {
		adsService.publish(getAdvertisement());
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Your advertisement was published. Can you see it?"));
	}

	public Advertisement getAdvertisement() {
		return advertisement;
	}

	public void setAdvertisement(Advertisement advertisement) {
		this.advertisement = advertisement;
	}

	public AdvertisementService getAdsService() {
		return adsService;
	}

	public void setAdsService(AdvertisementService adsService) {
		this.adsService = adsService;
	}
	
	
    
}
